package eu.credential.config.codesystems;

import eu.credential.wallet.notificationmanagementservice.model.Coding;

public enum CredentialIdentifiers_1_0 implements CodeSystem {

	ACCOUNTID("accountId", "Account ID of a CREDENTIAL user."), 
	EVENTID("eventId", "ID of an event that occured on the CREDENTIAL Wallet and is registered at the Notification Service"),
	PREFERENCEID("preferenceId", "ID of a preference created by a user"),
	SERVICEID("serviceId", "ID of a service"),
	NOTIFICATIONID("notificationId", "ID of a notification that was generated by the system");

	
	private static final String CODESYSTEM_NAME = "https://credential.eu/config/codesystems/identifiers";
	private static final String CODESYSTEM_VERSION = "1.0";
	
	private Coding coding;

	private CredentialIdentifiers_1_0(String code, String display) {
		coding = new Coding();
		coding.setCode(code);
		coding.setDisplay(display);
		coding.setSystem(CODESYSTEM_NAME);
		coding.setVersion(CODESYSTEM_VERSION);
	}

	public String getCode() {
		return coding.getCode();
	}

	public String getSystem() {
		return coding.getSystem();
	}

	public String getVersion() {
		return coding.getVersion();
	}

	public String getDisplay() {
		return coding.getDisplay();
	}

	public Coding getCoding() {
		return new Coding().code(getCode()).system(getSystem());
	}
	
	public Coding getCodingFull() {
		return coding;
	}

}

